# Generated by Django 4.0.3 on 2022-06-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idCombo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Combo')),
                ('NombreCombo', models.CharField(max_length=20, verbose_name='Nombre Combo')),
                ('Precio', models.IntegerField(verbose_name='Cantidad Combo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('nameUsuario', models.CharField(max_length=7, verbose_name='Nombre usuario')),
                ('contraseña', models.CharField(max_length=7, verbose_name='Contraseña usuario')),
                ('correo', models.CharField(max_length=7, verbose_name='Correo usuario')),
                ('telefono', models.IntegerField(verbose_name='Telefono usuario')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Pedido')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
        ),
    ]
