# Generated by Django 3.2.4 on 2021-06-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAdopcion',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Estado')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre del estado de la adopcion')),
            ],
        ),
        migrations.CreateModel(
            name='enAdopcion',
            fields=[
                ('idRescatado', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID del animal rescatado dado en adopcion')),
                ('nombre', models.CharField(default='Sin nombre', max_length=50, verbose_name='Nombre')),
                ('especie', models.CharField(default='Sin especie', max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(default='Sin raza', max_length=50, verbose_name='Raza')),
                ('descripcion', models.CharField(default='Sin descripcion', max_length=50, verbose_name='Descripcion')),
                ('edad', models.CharField(default='Sin edad', max_length=2, verbose_name='Edad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopciones.estadoadopcion')),
            ],
        ),
    ]
