# Generated by Django 3.2.4 on 2021-06-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoadopcion',
            old_name='nombreCategoria',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='estadoadopcion',
            old_name='idCategoria',
            new_name='estado_id',
        ),
    ]
