# Generated by Django 3.2.4 on 2021-06-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_auto_20210614_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enadopcion',
            old_name='estado',
            new_name='estado_id',
        ),
    ]
